### ISSUE TITLE
Task: Integrate and finalize eeg_fmri_cleaning

### ISSUE THREAD

**Issue by alperkent** [childmindresearch/eeg_research#11]
### Description

See Tasks.

### Tasks

- [x] Move all files into appropriate folders
- [x] Reorganize functions and classes into different files if necessary
- [x] Finalize the script and make sure the logic executes the correct cleaning pipeline
