### ISSUE TITLE
Task: Refactor gradient_remover.py

### ISSUE THREAD

**Issue by alperkent** [childmindresearch/eeg_research#2]
### Description

Refactor the `gradient_remover.py` script to make it able to read `mne.io.Raw` objects, include solution to remove trailing Gradient artifacts at start and end of recordings, and merge the code with the `utils.py` script.

### Tasks

- [ ] Modify `gradient_remover.py` to make it able to read `mne.io.Raw` objects
- [ ] Include solution to remove trailing Gradient artifacts at start and end of recordings
- [ ] Merge the code with the `utils.py` one
