### ISSUE TITLE
Task: Modify tools folder layout for preprocessing

### ISSUE THREAD

**Issue by alperkent** [childmindresearch/eeg_research#4]
### Description

Write general documentation, merge codes utils and functions, and remove all the functions that are not used in the pipelines.

### Tasks

- [ ]  Merge codes utils and functions
- [ ]  Remove all the functions that are not used in the pipelines
- [ ]  Write general documentation
