### ISSUE TITLE
Task: Refactor CLI code

### ISSUE THREAD

**Issue by alperkent** [childmindresearch/eeg_research#5]
### Description

The code in cli/pipelines needs some modifications:

The name of the python file needs to reflect what this code is about: it’s a command line interface that generates a bids layout. This module should be able to be used whatever the algorithm and whatever the modality. So it would be better if everything is wrapped into 1 class being CliBids or something like that. No need a `__main__` section because this module will not be called from the terminal but be used in other code if we want to integrate a CLI in these code. It needs to be flexible so no mention of any outside algorithm.

The `def main()` should be the pipeline (maybe put that into the object I mentioned earlier). The rest of the functions in the `eeg_fmri_cleaning.py` should go to `cli/tools`

### Tasks

- [x] Rename CLI files so that they are more descriptive
- [x] Refactor the code into a `cli_bids` class that wraps all related functions to generating a BIDS layout object
  - [x] Make sure that the class object does not need to refer to other scripts in the repo
- [x] Move any code other than the pipeline-related calls that should be under main() to cli/tools
