### ISSUE TITLE
Task: Integrate eeg_quality_assessment

### ISSUE THREAD

**Issue by alperkent** [childmindresearch/eeg_research#7]
### Description

See Tasks.

### Tasks

- [ ] Move `time_analysis` and `freq_analysis` into analysis/tools
- [ ] Move `signal_metrics` into analysis/pipelines
- [ ] Reorganize functions and classes into different files if necessary
